import { setCookie } from "./cookieStorage.js";
import { getCookie } from "./cookieStorage.js";
import { hasCookie } from "./cookieStorage.js";
import { removeCookie } from "./cookieStorage.js";
import { clearCookie } from "./cookieStorage.js";
import { isStorage } from "./isStorage.js";
import { isCookie } from "./isStorage.js";
import { setStorage } from "./itemStorage.js";
import { getStorage } from "./itemStorage.js";
import { hasStorage } from "./itemStorage.js";
import { removeStorage } from "./itemStorage.js";
import { clearStorage } from "./itemStorage.js";
export { setCookie, getCookie, hasCookie, removeCookie, clearCookie, isStorage, isCookie, setStorage, getStorage, hasStorage, removeStorage, clearStorage };
